version: '3'
services:
  postgres:
    container_name: e-commerce-postgresql
    image: postgres:latest
    environment:
      POSTGRES_DB: e-commerce-database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres-data:
    driver: local