spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/e-commerce-database
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

product-service:
  kafka:
    topics:
      # Исходящие события
      product-reserved: inventory.product.reserved.v1 # Успешная резервация
      product-failed: inventory.product.failed.v1 # Ошибка резервации

      # Входящие события
      order-created: order.order.created.v1 # Для инициации саги
      order-cancelled: order.order.cancelled.v1 # Для компенсаций
    group-id: ${spring.application.name}

server:
  port: 8082