spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/e-commerce-database
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092

product-service:
  kafka:
    topics:
      orders-event: order-events
      products-event: product-events

server:
  port: 8082